export enum ErrorType {
    UNPROCESSABLE_DATA = "UNPROCESSABLE_DATA",
    INVALID_ENTRY = "INVALID_ENTRY",
    DUPLICATE_DATA = "DUPLICATE_DATA",
    NOT_FOUND = "NOT_FOUND",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
  }
  