name: Tests

on:
  push:

jobs:
  jest:
    runs-on: ubuntu-latest
    env:
      TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
      PORT: ${{ secrets.PORT }}
      ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm ci

      - name: Build app
        run: |
          npm run build

      - name: Run Jest tests
        run: |
          npm test
